function createfigure(x1, y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 16-Dec-2010 03:55:32

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(x1,y1,'Parent',subplot1,'DisplayName','y vs. x');

% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
view(subplot2,[-37.5 30]);
grid(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(x1,y1,'Parent',subplot2,'DisplayName','y vs x');

