name: "pytorch_cifar10"
platform: "pytorch_libtorch"
max_batch_size : 0
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 32, 32 ]
    reshape { shape: [ 1, 3, 32, 32 ] }
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 10 ]
    reshape { shape: [ 1, 10 ] }
    label_filename: "cifar10_labels.txt"
  }
]
