/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sangwook_externallib_TrigonometricJni */

#ifndef _Included_com_sangwook_externallib_TrigonometricJni
#define _Included_com_sangwook_externallib_TrigonometricJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sangwook_externallib_TrigonometricJni
 * Method:    sin
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_sangwook_externallib_TrigonometricJni_sin
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_sangwook_externallib_TrigonometricJni
 * Method:    cos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_sangwook_externallib_TrigonometricJni_cos
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
