/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_Message */

#ifndef _Included_JNI_Message
#define _Included_JNI_Message
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_Message
 * Method:    Message
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_1Message_Message
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
