include config.mk

LIBS=$(LDFLAGS)
AUXILIARY_DEF=-mdll

DLLTOOL=dlltool
DLLWRAP=dllwrap
DLLWRAP_OPTION=

SHARED_LIB=libccv.dll
IMPORT_LIB=libccv.lib
DEF_FILE=libccv.def

LIB_OBJS=ccv_cache.o ccv_memory.o 3rdparty/sha1/sha1.o 3rdparty/kissfft/kiss_fft.o 3rdparty/kissfft/kiss_fftnd.o 3rdparty/kissfft/kiss_fftr.o 3rdparty/kissfft/kiss_fftndr.o 3rdparty/kissfft/kissf_fft.o 3rdparty/kissfft/kissf_fftnd.o 3rdparty/kissfft/kissf_fftr.o 3rdparty/kissfft/kissf_fftndr.o 3rdparty/dsfmt/dSFMT.o 3rdparty/sfmt/SFMT.o ccv_io.o ccv_numeric.o ccv_algebra.o ccv_util.o ccv_basic.o ccv_resample.o ccv_transform.o ccv_classic.o ccv_daisy.o ccv_sift.o ccv_bbf.o ccv_mser.o ccv_swt.o ccv_dpm.o ccv_tld.o ccv_ferns.o

#CC += -faddress-sanitizer -fno-omit-frame-pointer
CFLAGS := -O3 -ffast-math -Wall $(AUXILIARY_DEF) $(CFLAGS)# -fprofile-arcs -ftest-coverage

.PHONY: all clean

all: $(SHARED_LIB)

clean:
	rm -f *.o 3rdparty/sha1/*.o 3rdparty/sfmt/*.o 3rdparty/kissfft/*.o 3rdparty/dsfmt/*.o $(SHARED_LIB) $(IMPORT_LIB) $(DEF_FILE)

$(SHARED_LIB): $(LIB_OBJS) $(IMPORT_LIB) $(DEF_FILE)
	$(DLLWRAP) $(DLLWRAP_OPTION) --def $(DEF_FILE) --dllname=$@ $(LIB_OBJS) $(LIBS)

$(IMPORT_LIB) : $(DEF_FILE)
	$(DLLTOOL) --input-def=$< --output-lib=$@ --dllname=$(SHARED_LIB)

$(DEF_FILE) : $(LIB_OBJS)
	$(DLLTOOL) --kill-at --export-all --output-def=$@ $^

ccv_io.o: ccv_io.c ccv.h ccv_internal.h io/*.c
	$(CC) $< -o $@ -c $(CFLAGS)

%.o: %.c ccv.h ccv_internal.h
	$(CC) $< -o $@ -c $(CFLAGS)
