/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sangwook_simpleapp_ArithmeticJni */

#ifndef _Included_com_sangwook_simpleapp_ArithmeticJni
#define _Included_com_sangwook_simpleapp_ArithmeticJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sangwook_simpleapp_ArithmeticJni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sangwook_simpleapp_ArithmeticJni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sangwook_simpleapp_ArithmeticJni
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sangwook_simpleapp_ArithmeticJni_sub
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
