// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HypothesisList.proto

#ifndef PROTOBUF_HypothesisList_2eproto__INCLUDED
#define PROTOBUF_HypothesisList_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_HypothesisList_2eproto();
void protobuf_InitDefaults_HypothesisList_2eproto();
void protobuf_AssignDesc_HypothesisList_2eproto();
void protobuf_ShutdownFile_HypothesisList_2eproto();

class HypothesisList;
class HypothesisList_ObjectHypothesis;

// ===================================================================

class HypothesisList_ObjectHypothesis : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:HypothesisList.ObjectHypothesis) */ {
 public:
  HypothesisList_ObjectHypothesis();
  virtual ~HypothesisList_ObjectHypothesis();

  HypothesisList_ObjectHypothesis(const HypothesisList_ObjectHypothesis& from);

  inline HypothesisList_ObjectHypothesis& operator=(const HypothesisList_ObjectHypothesis& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HypothesisList_ObjectHypothesis& default_instance();

  static const HypothesisList_ObjectHypothesis* internal_default_instance();

  void Swap(HypothesisList_ObjectHypothesis* other);

  // implements Message ----------------------------------------------

  inline HypothesisList_ObjectHypothesis* New() const { return New(NULL); }

  HypothesisList_ObjectHypothesis* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HypothesisList_ObjectHypothesis& from);
  void MergeFrom(const HypothesisList_ObjectHypothesis& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HypothesisList_ObjectHypothesis* other);
  void UnsafeMergeFrom(const HypothesisList_ObjectHypothesis& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // optional float scale = 3;
  bool has_scale() const;
  void clear_scale();
  static const int kScaleFieldNumber = 3;
  float scale() const;
  void set_scale(float value);

  // optional float score = 4;
  bool has_score() const;
  void clear_score();
  static const int kScoreFieldNumber = 4;
  float score() const;
  void set_score(float value);

  // optional bool flip = 5 [default = false];
  bool has_flip() const;
  void clear_flip();
  static const int kFlipFieldNumber = 5;
  bool flip() const;
  void set_flip(bool value);

  // @@protoc_insertion_point(class_scope:HypothesisList.ObjectHypothesis)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_scale();
  inline void clear_has_scale();
  inline void set_has_score();
  inline void clear_has_score();
  inline void set_has_flip();
  inline void clear_has_flip();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  float x_;
  float y_;
  float scale_;
  float score_;
  bool flip_;
  friend void  protobuf_InitDefaults_HypothesisList_2eproto_impl();
  friend void  protobuf_AddDesc_HypothesisList_2eproto_impl();
  friend void protobuf_AssignDesc_HypothesisList_2eproto();
  friend void protobuf_ShutdownFile_HypothesisList_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<HypothesisList_ObjectHypothesis> HypothesisList_ObjectHypothesis_default_instance_;

// -------------------------------------------------------------------

class HypothesisList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:HypothesisList) */ {
 public:
  HypothesisList();
  virtual ~HypothesisList();

  HypothesisList(const HypothesisList& from);

  inline HypothesisList& operator=(const HypothesisList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HypothesisList& default_instance();

  static const HypothesisList* internal_default_instance();

  void Swap(HypothesisList* other);

  // implements Message ----------------------------------------------

  inline HypothesisList* New() const { return New(NULL); }

  HypothesisList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HypothesisList& from);
  void MergeFrom(const HypothesisList& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HypothesisList* other);
  void UnsafeMergeFrom(const HypothesisList& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef HypothesisList_ObjectHypothesis ObjectHypothesis;

  // accessors -------------------------------------------------------

  // repeated .HypothesisList.ObjectHypothesis hyp = 1;
  int hyp_size() const;
  void clear_hyp();
  static const int kHypFieldNumber = 1;
  const ::HypothesisList_ObjectHypothesis& hyp(int index) const;
  ::HypothesisList_ObjectHypothesis* mutable_hyp(int index);
  ::HypothesisList_ObjectHypothesis* add_hyp();
  ::google::protobuf::RepeatedPtrField< ::HypothesisList_ObjectHypothesis >*
      mutable_hyp();
  const ::google::protobuf::RepeatedPtrField< ::HypothesisList_ObjectHypothesis >&
      hyp() const;

  // @@protoc_insertion_point(class_scope:HypothesisList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::HypothesisList_ObjectHypothesis > hyp_;
  friend void  protobuf_InitDefaults_HypothesisList_2eproto_impl();
  friend void  protobuf_AddDesc_HypothesisList_2eproto_impl();
  friend void protobuf_AssignDesc_HypothesisList_2eproto();
  friend void protobuf_ShutdownFile_HypothesisList_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<HypothesisList> HypothesisList_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HypothesisList_ObjectHypothesis

// optional float x = 1;
inline bool HypothesisList_ObjectHypothesis::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HypothesisList_ObjectHypothesis::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HypothesisList_ObjectHypothesis::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HypothesisList_ObjectHypothesis::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float HypothesisList_ObjectHypothesis::x() const {
  // @@protoc_insertion_point(field_get:HypothesisList.ObjectHypothesis.x)
  return x_;
}
inline void HypothesisList_ObjectHypothesis::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:HypothesisList.ObjectHypothesis.x)
}

// optional float y = 2;
inline bool HypothesisList_ObjectHypothesis::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HypothesisList_ObjectHypothesis::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HypothesisList_ObjectHypothesis::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HypothesisList_ObjectHypothesis::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float HypothesisList_ObjectHypothesis::y() const {
  // @@protoc_insertion_point(field_get:HypothesisList.ObjectHypothesis.y)
  return y_;
}
inline void HypothesisList_ObjectHypothesis::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:HypothesisList.ObjectHypothesis.y)
}

// optional float scale = 3;
inline bool HypothesisList_ObjectHypothesis::has_scale() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HypothesisList_ObjectHypothesis::set_has_scale() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HypothesisList_ObjectHypothesis::clear_has_scale() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HypothesisList_ObjectHypothesis::clear_scale() {
  scale_ = 0;
  clear_has_scale();
}
inline float HypothesisList_ObjectHypothesis::scale() const {
  // @@protoc_insertion_point(field_get:HypothesisList.ObjectHypothesis.scale)
  return scale_;
}
inline void HypothesisList_ObjectHypothesis::set_scale(float value) {
  set_has_scale();
  scale_ = value;
  // @@protoc_insertion_point(field_set:HypothesisList.ObjectHypothesis.scale)
}

// optional float score = 4;
inline bool HypothesisList_ObjectHypothesis::has_score() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void HypothesisList_ObjectHypothesis::set_has_score() {
  _has_bits_[0] |= 0x00000008u;
}
inline void HypothesisList_ObjectHypothesis::clear_has_score() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void HypothesisList_ObjectHypothesis::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline float HypothesisList_ObjectHypothesis::score() const {
  // @@protoc_insertion_point(field_get:HypothesisList.ObjectHypothesis.score)
  return score_;
}
inline void HypothesisList_ObjectHypothesis::set_score(float value) {
  set_has_score();
  score_ = value;
  // @@protoc_insertion_point(field_set:HypothesisList.ObjectHypothesis.score)
}

// optional bool flip = 5 [default = false];
inline bool HypothesisList_ObjectHypothesis::has_flip() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void HypothesisList_ObjectHypothesis::set_has_flip() {
  _has_bits_[0] |= 0x00000010u;
}
inline void HypothesisList_ObjectHypothesis::clear_has_flip() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void HypothesisList_ObjectHypothesis::clear_flip() {
  flip_ = false;
  clear_has_flip();
}
inline bool HypothesisList_ObjectHypothesis::flip() const {
  // @@protoc_insertion_point(field_get:HypothesisList.ObjectHypothesis.flip)
  return flip_;
}
inline void HypothesisList_ObjectHypothesis::set_flip(bool value) {
  set_has_flip();
  flip_ = value;
  // @@protoc_insertion_point(field_set:HypothesisList.ObjectHypothesis.flip)
}

inline const HypothesisList_ObjectHypothesis* HypothesisList_ObjectHypothesis::internal_default_instance() {
  return &HypothesisList_ObjectHypothesis_default_instance_.get();
}
// -------------------------------------------------------------------

// HypothesisList

// repeated .HypothesisList.ObjectHypothesis hyp = 1;
inline int HypothesisList::hyp_size() const {
  return hyp_.size();
}
inline void HypothesisList::clear_hyp() {
  hyp_.Clear();
}
inline const ::HypothesisList_ObjectHypothesis& HypothesisList::hyp(int index) const {
  // @@protoc_insertion_point(field_get:HypothesisList.hyp)
  return hyp_.Get(index);
}
inline ::HypothesisList_ObjectHypothesis* HypothesisList::mutable_hyp(int index) {
  // @@protoc_insertion_point(field_mutable:HypothesisList.hyp)
  return hyp_.Mutable(index);
}
inline ::HypothesisList_ObjectHypothesis* HypothesisList::add_hyp() {
  // @@protoc_insertion_point(field_add:HypothesisList.hyp)
  return hyp_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::HypothesisList_ObjectHypothesis >*
HypothesisList::mutable_hyp() {
  // @@protoc_insertion_point(field_mutable_list:HypothesisList.hyp)
  return &hyp_;
}
inline const ::google::protobuf::RepeatedPtrField< ::HypothesisList_ObjectHypothesis >&
HypothesisList::hyp() const {
  // @@protoc_insertion_point(field_list:HypothesisList.hyp)
  return hyp_;
}

inline const HypothesisList* HypothesisList::internal_default_instance() {
  return &HypothesisList_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_HypothesisList_2eproto__INCLUDED
